export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const REMOVE_USER = "REMOVE_USER";

export const GET_PROCESSES_BEGIN = "GET_PROCESSES_BEGIN";
export const GET_PROCESSES_SUCCES = "GET_PROCESSES_SUCCES";

export const GET_INSTRUCTIONS = "GET_INSTRUCTIONS";
export const GET_INSTRUCTIONS_BEGIN = "GET_INSTRUCTIONS_BEGIN";
